from django.contrib import admin
from django.urls import path
from core.views import home_view, about_view, contact_view, register_view, dashboard_view, login_view, profile_view, edit_profile_view, subject_list_view, add_subject_view, edit_subject_view, delete_subject_view, topic_list_view, add_topic_view, toggle_topic_view, edit_topic_view, delete_topic_view, study_plan_view, add_study_plan_view, delete_study_plan_view, task_list_view, add_task_view, edit_task_view, delete_task_view, toggle_task_view, goal_list_view, add_goal_view, edit_goal_view, delete_goal_view, analytics_view, notification_list_view, delete_notification_view, portfolio_view, portfolio_contact_view, add_study_activity_view, study_activity_list_view, smart_priority_view

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('admin/', admin.site.urls),
    path('register/', register_view, name='register'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('login/', login_view, name='login'),
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', edit_profile_view, name='edit_profile'),
    path('subjects/', subject_list_view, name='subjects'),
    path('subjects/<int:subject_id>/topics/', topic_list_view, name='topics'),
    path('subjects/<int:subject_id>/topics/add/', add_topic_view, name='add_topic'),
    path('subjects/add/', add_subject_view, name='add_subject'),
    path('subjects/<int:subject_id>/delete/', delete_subject_view, name='delete_subject'),
    path('subjects/<int:subject_id>/edit/', edit_subject_view, name='edit_subject'),
    path('topics/<int:topic_id>/toggle/', toggle_topic_view, name='toggle_topic'),
    path('topics/<int:topic_id>/edit/', edit_topic_view, name='edit_topic'),
    path('topics/<int:topic_id>/delete/', delete_topic_view, name='delete_topic'),
    path('study-plans/', study_plan_view, name='study_plans'),
    path('study-plans/add/', add_study_plan_view, name='add_study_plan'),
    path('study-plans/<int:study_plan_id>/delete/', delete_study_plan_view, name='delete_study_plan'),
    path('tasks/', task_list_view, name='tasks'),
    path('tasks/add/', add_task_view, name='add_task'),
    path('tasks/<int:task_id>/edit/', edit_task_view, name='edit_task'),
    path('tasks/<int:task_id>/delete/', delete_task_view, name='delete_task'),
    path('tasks/<int:task_id>/toggle/', toggle_task_view, name='toggle_task'),
    path('goals/', goal_list_view, name='goals'),
    path('goals/add/', add_goal_view, name='add_goal'),
    path('goals/<int:goal_id>/edit/', edit_goal_view, name='edit_goal'),
    path('goals/<int:goal_id>/delete/', delete_goal_view, name='delete_goal'),
    path('analytics/', analytics_view, name='analytics'),
    path('portfolio/', portfolio_view, name='portfolio'),
    path('notifications/', notification_list_view, name='notifications'),
    path('notifications/<int:notification_id>/delete/',delete_notification_view,name='delete_notification'),
    path('portfolio/contact/', portfolio_contact_view, name='portfolio_contact'),
    path('study-activity/add/', add_study_activity_view, name='add_study_activity'),
    path('study-activity/', study_activity_list_view, name='study_activity'),
    path('smart-priority/', smart_priority_view, name='smart_priority'),
]